import random
import sys

print("""DataBase 12月考査
v1.0
""")


J = ["その自動車修理工場は1時間の労働につき50ドル請求する。",
"彼は事務員の仕事に就いた。",
"私たちの最初の仕事は情報を集めることだ。",
"私の職業は建築家だ。",
"あなたの名前、住所、職業を述べてください。",
"新郎新婦は馬車でやって来た。",
"あなたの私物を航空貨物で送ってあげましょう。",
"その飛行機は燃料を満載していた。",
"その運転手は運転中に眠り込んだに違いない。",
"昨夜、雨が激しく降った。",
"私は君の言うことがほとんど聞こえなかった。",
"ちょうどそのとき、私の背後から叫び声が聞こえた。",
"警察はその男を公正に扱った。",
"彼女は1時間遅れて会議にやって来た。",
"あなたは最近、何をしていましたか。",
"彼は私の近くにやって来て、ほほえんだ。",
"彼女はもう少しで花瓶を落とすところだった。",
"彼女がタイで生きているという噂を聞いた。",
"彼らは、この山の頂上からの夜景はたいへん貴重だという。",
"この価値のない機械が非常に多くの問題を引き起こしたので、私はそれを処分する予定だ。",
"探していたまさにそのネックレスを見つけたので、私はとてもうれしかった。",
"インドの友人は、それはもっとも素晴らしいカレーだと言った。",
"地球の表面は主に水である。",
"そのテーブルには注意してください、それはかなり重いです。",
"子どもたちはステージでかわいらしく歌を歌った。",
"3時きっかりにここに来てください。",
"新潟で作られたこの台所用ナイフはかなり鋭く切れる。",
"端数のない数字で3万円だ。",
"総費用はこの2つの額の合計だ。",
"50グラムのバター、そして同じ量の砂糖を加えなさい。",
"100の4分の1は25だ。",
"先月その会社の利益は2倍になった。",
"その果物は飛行機で輸送された。",
"大阪事業所の閉鎖に伴って、職員は東京事業所へ転勤することになる。",
"少年時代に、彼は山々を歩き回って多くの時間を過ごした。",
"その建物の土台がほんの少しずれた。",
"バスは午前10時に出発する予定だった。",
"その情報は図表で伝えることができる。",
"飛行機が下降し始めた。",
"ジョンは3年前、日本に移住した。",
"ジムは教育委員会の委員長に任命された。",
"教職員組合は来週、年次協議会を開催する予定だ。",
"あの会社は財政上の危機に陥った。",
"彼の会社がインドに移転したと誰かから聞いた。",
"今朝、新聞で宇宙ステーションについての記事を読んだ。",
"マイクは非常に優れた経営者だ。",
"私の秘書が詳細をすべて送ります。",
"私はこの手紙にちょっとあなたの署名をいただきたい。",
"ベイカー氏が報告書を書く仕事を引き受けた。",
"政府はまだ経済状態をよくするという公約を果たしていない。",
"早稲田大学は、1882年に大隈重信によって設立された。",
"その川を渡る新たな橋を建設する計画がある。",
"温室の中は一定の温度を維持することが重要だ。",
"その音楽家はさまざまなボランティア活動に従事している。",
"彼女は紙片に自分の住所を書いた。",
"職員は皆、研修コースへの参加を勧められている。",
"彼はおしゃれなスーツとネクタイを身につけていた。",
"この仕事はいくらか手作業を必要とする。",
"心配しないで、私がこれに対処します。",
"この地域ではかなり多量の雪が降る。",
"あなたはどの銘柄のシャンプーを使っていますか。",
"彼女は私の昇進を温かく祝ってくれた。",
"業者は私にその品質を保証していた。",
"医師団は彼が自然死であったと断言した。",
"要点を説明するために、実例を挙げましょう。",
"いくつかの研究が喫煙とがんの関連性を明確に示している。",
"彼女の絵は世界中で展示されている。",
"それはその聖地への私たちの初めての訪問だった。",
"彼らの魂に神の慈悲がありますよう。",
"私はあまり信心深くないが、よく先祖の墓参りをする。",
"彼女は罪を告白して、許しを請う必要があった。",
"私は依然として彼に信頼をおいていた。",
"ロバートは、最後には成功するという固い信念をもっている。",
"彼女はオリンピックで金メダルをとり、自国に栄光をもたらした。",
"その都市はユダヤ教徒とイスラム教徒の聖都だ。",
"キリスト教徒は死後に永遠の命があると信じている。",
"古代エジプト人は多くの神々を崇拝した。",
"さあ、神に成功を祈りましょう。",
"その若い芸術家は美的センスに恵まれている。",
"彼は2人の若者を射殺したことを認めた。",
"私は、自分の自主性を犠牲にしたくなかった。",
"記者団が裁判所の外に集まった。",
"彼は弁護士が来るまで、いかなる質問にも答えることを拒んでいる。",
"これは彼女の無実を示すさらなる証拠だ。",
"私たちの目的は犯罪の被害者たちを支援することだ。",
"目撃者の話だと、小さい飛行機が大きい方に突っ込んだということだ。",
"裁判は数ヶ月続く可能性がある。",
"霧は大気中のたくさんの水滴からできている。",
"昨年、その町はこの50年で最悪の洪水に見舞われた。",
"典型的な秋晴れの日だった。",
"花がそよ風に揺れていた。",
"地面は霜が降りて真っ白だった。",
"彼の両手は汗で湿っていた。",
"東京は真夏にはとても湿気が多い。",
"温度計は摂氏40度より上を表示していた。",
"突然、大きな雷鳴がとどろいた。",
"私の弁護団が契約書を作成した。",
"裁判所は彼に無罪の判決を下し、彼は釈放された。",
"私たちは全市民のために公正と平等な権利を要求する。",
"その会社のしたことは完全に合法である。",
"彼は自分の犯していない罪[冤罪]で11年間刑務所に入っていた。",
"ジャガイモは光にさらされると緑色になる。",
"春になると昆虫が現れる。",
"その情報はまず日曜の新聞で明らかにされた。",
"私はあなたが嘘をついているとほのめかすつもりはなかった。",
"交渉の中でいくつかの重要な法律上の問題が生じた。",
"フランスは自国の電気の大部分を原子力から生み出す。",
"彼女は胸に変な痛みを感じた。",
"ようやく救急車が来た。",
"私が失敗した後、友だち皆が私を慰めようとしてくれた。",
"その生徒は自信過剰で、先生の忠告を聞こうとしなかった。",
"親は麻薬乱用の危険性について、子供に率直に話すべきだ。",
"サムの顔は疲労で青ざめていた。",
"筋肉は脂肪より重い。",
"ニンニクはかぜを治すのに有効である。",
"症状は頭痛や食欲不振などです。",
"彼の顔に汗がどっと流れていた。",
"バクテリアは地球上で何億年も前から生存している。",
"私たちはまだ明日の会議の準備をしていない。",
"全室にビデオカメラが備えられている。",
"そのホテルにはアンティークの家具が備え付けられている。",
"『美女と野獣』は有名な童話だ。",
"彼女は生物学の学位を持っている。",
"植物学とは植物の科学的な研究だ。",
"胚は細胞分裂によって成長する。",
"生態学は生物とその環境を調査する。",
"鳥だけが羽毛を持ち、それは鳥の体のほとんどすべての部分を覆っている。",
"哺乳動物の毛皮は寒い天候の時に体を温かい状態に保つ。",
"私が窓を開けるたびに、昆虫が飛び込んできた。",
"あらゆる動物に強い生存本能がある。",
"ダーウィンは進化がどのようにして起こるかを説明した。",
"彼はブリストル大学で教育を受けた。",
"何が起こったのか私はまだ理解していない。",
"その研究は失業の影響を調査している。",
"外国を旅すれば、文化的な差異を多く学ぶだろう。",
"私は民族舞踊や民族音楽が好きだ。",
"私たちは全人類のために清潔で健全な環境を望む。",
"地元住民はショッピング・センターを建設する計画に反対している。",
"仮設宿泊所の状態は極めて原始的だった。",
"警察が、男性5人を殺害した残忍な殺人犯を捜索中だ。",
"彼らは彼女を奴隷のように扱った。",
"その部族の人たちは伝統的な衣装を身につけていた。",
"私の友達はとても興味深い民族的背景を持っている。",
"工場の仕事の多くが、出稼ぎ労働者によってなされている。",
"子供たちはすぐに善と悪を区別することができるようになる。",
"そのチームの監督の座はシーズンの終わりに再検討されるだろう。",
"植物は土壌から養分を吸収する。",
"私の兄[弟]は最近テレビゲームで遊ぶことに夢中になっている。",
"牛が草原で草を食べている。",
"多量の雨と高温の気候、肥えた土地が良質の米を産出する。",
"ペストは1600年代にロンドンだけで10万人の死者を出した。",
"私の兄[弟]は田舎の生活にうんざりしているようだ。",
"私はずっと裏庭で雑草を取っていた。",
"オーストラリアは多くの国に小麦を輸出している。",
"パンやケーキ、パスタは小麦粉から作られる。",
"土壌の質で農作物の産出量はある程度決まる。",
"ついに彼は誘惑に負けた。",
"有機農業は環境によりやさしい。",
"これらの棒を一緒に縄で縛ってください。",
"アランはドアの取っ手をしっかり握って引いた。",
"彼はとてもうまくその状況を処理した。",
"母はレモンの汁をしぼってサラダにかけた。",
"次の選挙には5人の候補者がいる。",
"その国は内戦によって引き裂かれてきた。",
"米国大統領は連邦議会に対して演説を行った。",
"日本国憲法には、私たちは決して戦争を開始しないと書いてある。",
"オランダはヨーロッパの北西部にある王国だ。",
"我に自由を与えよ、しからずんば死を与えよ。",
"この会議では好きなことを何でも自由に言うことができる。",
"その国は軍事力を行使する準備ができている。",
"彼女はスプーンでコーヒーをかき回した。",
"ブラッドはずたずたにその手紙を裂いて、ゴミ箱に捨てた。",
"ウエイターはテーブルを拭いていた。",
"彼女はセーターをもう2枚カバンに詰め込んだ。",
"その法案は4月に国会で可決された。",
"今や教育は重要な政治課題だ。",
"9つの共和国が国民投票に参加した。",
"ロシアの外務大臣も会議に出席していた。",
"教育制度に大変革があった。",
"長距離ミサイル削減の条約が調印された。",
"皆が驚いたことに、その有名な俳優はあの州の知事に選ばれた。",
"私たちは来月サンフランシスコでのコンピュータ会議に行くつもりだ。",
"奴隷制度は米国では19世紀に廃止された。",
"彼は殺人罪で告発されている。",
"彼は酒気帯び運転の罪を犯した。",
"彼は祖父から財産を相続した。",
"原子の内部には信じられないくらいのエネルギーが蓄えられている。",
"科学者たちは多量のデータを集めた。",
"米国の海軍は多くの原子力潜水艦を保有している。",
"酸素は生命に不可欠である。",
"水素はあらゆる気体の中でもっとも軽い。",
"私たちは地球が完全な球ではないことを知っている。",
"それぞれのサンプルは顕微鏡で検査された。",
"ありふれた食卓塩である塩化ナトリウムは、人間の生活に欠かせない。",
"近い将来、酸性雨はさらなる論争を引き起こす問題になるだろう。",
"私は議長に任命された。",
"同じ政党が12年間にわたってその国を統治している。",
"政府はたばこに新たな税を課した。",
"彼女は金融街で働いている。",
"地形はそこの住民にどんな影響を及ぼしてきたのでしょうか。",
"私たちは世界中に私たちの製品を輸出している。",
"自由の女神像は、ニューヨーク市の港にある島に立っている。",
"スコールは熱帯地方でよく見られる。",
"これが駅へ行くもっとも早い道筋だ。",
"香港は1997年に再び中国領となった。",
"大気汚染の問題は都市部で特に深刻だ。",
"学生は幅広い範囲の科目の中から選択できる。",
"非常に多くの人々がその戦争に抗議した。",
"多くの人が新法に反対した。",
"私が話しているときは口を挟まないでください。",
"雨で、私たちがハイキングに行く計画に支障を来すかもしれない。",
"みんなが私の服をからかった。",
"彼女は話をすべてでっちあげた。",
"私は朝食を食べないが、昼食でそれを補っている。",
"私たちはその犯人の年齢を考慮に入れなければならない。",
"私は仕事と遊びとを混同しないことにしている。",
"あなたは来月の予定を作りましたか。",
"彼女がもう1つ質問をしようとしたとたんに、ジョージが話に割り込んだ。",
"私たちはそのレストランの正面に車を止めた。",
"本気じゃないでしょ。私をからかっているんでしょ。",
"私たちは解決策を思いついたと思う。",
"私たちは子どもの教育のことで口論した。",
"その映画は実際のところ私たちの期待に応えていなかった。",
"彼は自分が犯した犯罪の責任を負うべきだ。",
"私はシャツにコーヒーをこぼしたので、着替える必要がある。",
"新宿駅で電車を乗り換える必要がある。",
"インタビューの始めに握手するのは習慣である。",
"技術的には、私たちの設備は少し時代遅れだ。",
"生存者はまだ1人も見つかっていない。",
"そのコンサートのチケットは前もって手に入れておいた方がいい。",
"今出れば、私はすぐに帰れる。",
"まもなく夏休みが終わる。",
"悪の帝国は永久に滅びた。",
"私たちはよく公園に散歩に行ったものだった。",
"私の両親があなたに会いたいと思っている。",
"夜に自転車に乗るときはいくら注意してもしすぎではない。",
"私は君にいくら感謝してもし足りない。",
"君が彼に腹を立てるのももっともだ。",
"何もありそうにないから、私たちは家に帰ったほうがよい。",
"君はそんな無意味なことにお金を使うくらいなら捨てたほうがましだ。",
"君はよくもずうずうしく私にそんな口がきけるね。",
"その企画の担当をしているのは誰ですか。",
"子供をしつけるのは親の責任だ。",
"スミスはまだ得点していない。",
"おじは裕福であるが、とても質素に暮らしている。",
"君が皿洗いを終えたら、買い物に行こう。",
"その列車衝突事故の原因を究明するための調査が進行中だ。",
"私はもう新しいアパートに慣れた。",
"最近、私は近所の人たちと仲が良い。",
"大統領は所得税減税を約束し、その約束通りに実行している。",
"君の言っていることは的外れだ。",
"私は、腹が立つというよりむしろ心配だった。",
"彼らは出て行くとき、別れのあいさつさえしなかった。",
"日本では桜の花はどの花にも劣らず美しいと、私は思う。",
"200万人もの観光客が、毎年ここにやってくる。",
"もし食事代を自腹で払うのならば、君も一緒に来ていいよ。",
"名前を明かさないという条件で、2人の従業員が私たちに話をすることに同意してくれた。",
"彼女とは二度と口をきかない。たとえ彼女が謝ってきたとしても。",
"その車は古いけれども、まだよく走る。",
"前もって予約しない限り、君はそのチケットを入手できない。",
"小さくはあるが、これはすごい価値があるものだ。",
"旧制度は複雑だった。ところがそれに対して新制度はとても単純だ。",
"あなたが賛成しようがしまいが、私たちはそれを実行します。",
"世論調査によると30%の人しか政府を信頼していない。",
"私は彼女とせいぜい30分しか話さなかった。",
"彼はCDを300枚も持っている。",
"ここからその駅まで歩くには少なくとも40分はかかるだろう。",
"車の運転(がやさしくないの)と同様に飛行機の操縦はやさしくない。",
"エジソン(が天才であったの)と同様に、ワットは天才であった。",
"私たちはフランクフルト経由でリオ・デ・ジャネイロへ飛んだ。",
"ウォルターはそのお金を必ず返すと約束した。",
"ばかばかしい結末を除けば、その映画はすばらしかった。",
"この種のイベントはすべての人の好みに合っているというわけではない。",
"彼女に明日電話しよう。いや、考え直して[やっぱり]、今しよう。",
"その自転車窃盗犯たちはまだ捕まっていないそうだ。",
"彼のいないところで彼を批判するな。",
"たくさん眠れば眠るほど、ますます気分が楽になりますよ。",
"母は3日間休暇を取ったのでますます元気になったように見える。",
"新しい助手がいるからといって私の仕事が楽になったわけではない。",
"彼女は、彼があの特定の声色を使ったときに、彼と口論するほど愚かではなかった。",
"彼女は自分で事業を始めることに関心がある。",
"その伝説はこの村のすべての人に知られている。",
"人はその人がつき合っている友人でわかる。《諺》",
"私の古い机は埃で覆われていた。",
"私たちはひどい吹雪にあった。"]

E_sentence = ["The garage charges 50 dollars an hour for (l      ).",
"He got a (j     ) as a clerk.",
"Our first (t      ) is to gather information.",
"I'm an architect by (p      ).",
"Please state your name, address and (o      ).",
"The bride and groom arrived in a horse-drawn (c      ).",
"We'll send your personal belongings by air (f      ).",
"The plane was carrying a full (l      ) of fuel.",
"The driver must have fallen asleep at the (w      ).",
"It rained (h      ) last night.",
"I could (h      ) hear what you said.",
"(J      ) then I heard a cry behind me.",
"The police treated the man (j      ).",
"She came to the meeting an hour (l      ).",
"What have you been doing (l      )?",
"He came (n      ) me and smiled.",
"She (n      ) dropped the vase.",
"I heard a rumor that she is (l      ) in Thailand.",
"The say the nightview from the top of this mountain is (p      ).",
"This (w      ) machine has caused so many problems so I'm getting rid of it.",
"I was so happy because I found the (v      ) necklace I was looking for.",
"My friends from India said it was the (m      ) wonderful curry.",
"The surface of the planet Earth is (m      ) water.",
"Be careful with that table; it's (p      ) heavy.",
"The children sang the song (p      ) on the stage.",
"Please come here at three (s      ).",
"This kitchen knife which was made in Niigata can cut quite (s      ).",
"It's about 30,000 yen in round (f      ).",
"The total cost is the (s      ) of these two amounts.",
"Add 50 grams of butter, and the same (q      ) of sugar.",
"A (q      ) of 100 is 25.",
"The company's profits (d      ) last month.",
"That fruit was (t      ) by air.",
"The Osaka office is closing and the staff will (t      ) to the Tokyo office.",
"As a boy, he spent a lot of time (w      ) in the mountains.",
"The building's foundation has (s      ) slightly.",
"The bus was due to (d      ) at 10:00 a.m.",
"The information can be (c      ) in a diagram.",
"The plane started to (d      ).",
"John (i      ) to Japan three years ago.",
"Jim was appointed (c      ) of the education committee.",
"The teachers' union is holding its annual (c      ) next week.",
"That company fell into a (f      ) crisis.",
"Someone told me his (f      ) had moved to India.",
"This morning I read an (i      ) about the space station in the paper.",
"Mike is a very good (m      ).",
"My (s      ) will send you all the details.",
"I just need your (s      ) on this letter.",
"Mr. Baker (u      ) the job of writing the report.",
"The government has not yet (f      ) its promise to improve the economy.",
"Waseda University was (e      ) in 1882 by Okuma Shigenobu.",
"There are plans to (c      ) a new bridge across the river.",
"It is important to (m      ) a constant temperature inside the greenhouse.",
"That musician is (e      ) in various volunteer activities.",
"She wrote her address on a (s      ) of paper.",
"Everyone on the (s      ) is encouraged to attend training courses.",
"He was dressed in a stylish (s      ) and tie.",
"This job requires some (m      ) labor.",
"Don't worry, I'll (d      ) with this.",
"We get a good (d      ) of snow in this area.",
"What (b      ) of shampoo do you use?",
"She (c      ) me warmly on my promotion.",
"The dealer had (a      ) me of its quality.",
"Doctors (d      ) that he died of natural causes.",
"Let me give an example to (i      ) the point.",
"Several studies have (d      ) a link between smoking and cancer.",
"Her painting have been (e      ) all over the world.",
"It was our first visit to that (h      ) place.",
"May God have (m      ) on their souls.",
"I'm not very (r      ), but I often visit my ancestors' graves.",
"She needed to confess her (s      ) and ask for forgiveness.",
"I still had (f      ) in him.",
"Robert has a firm (b      ) that he will succeed in the end.",
"She brought (g      ) to her country by winning the gold medal at the Olympics.",
"The city is (s      ) to Jews and Muslims.",
"Christians believe in (e      ) life after death.",
"The ancient Egyptians (w      ) many gods.",
"Let's (p      ) to God for success.",
"The young artist is (b      ) with a sense of beauty.",
"He (c      ) to shooting the two young men.",
"I didn't want to (s      ) my independence.",
"A group of reporters gathered outside the (c      ).",
"He refuses to answer any questions until his (l      ) comes.",
"This is further (p      ) of her innocence.",
"Our aim is to help (v      ) of crime.",
"(W      ) say the smaller plane flew into the larger one.",
"The (t      ) could last several months.",
"(F      ) is made up of lots of drops of water in the air.",
"Last year, the town suffered the worst (f      ) in 50 years.",
"It was a (t      ) clear autumn day.",
"Flowers were waving in the (b      ).",
"The ground was white with (f      ).",
"His hands were (m      ) with sweat.",
"Tokyo is very (h      ) in midsummer.",
"The (t      ) registered over 40 degrees Celcius.",
"Suddenly there was a great crash of (t      ).",
"My lawyers have drawn up a (c      ).",
"The court found him (i      ) and he was released.",
"We demand (j      ) and equal rights for all citizens.",
"What the company has done is perfectly (l      ).",
"He spent eleven years in (p      ) for a crime he had not committed.",
"Potatoes turn green when (e      ) to light.",
"Insects (e      ) in the spring.",
"The information was first (r      ) in the Sunday newspaper.",
"I didn't mean to (i      ) that you were lying.",
"Several important legal questions (a      ) during the negotiations.",
"France (g      ) a large part of its electricity from nuclear power.",
"She felt a strange (a      ) in her chest.",
"At last the (a      ) came.",
"All my friends tried to (c      ) me after my failure.",
"The student was overconfident and (d      ) to his teacher's advice.",
"Parents should talk openly to their children about the dangers of (d      ) abuse.",
"Sam's face was pale with (f      ).",
"(M      ) weighs more than fat.",
"Garlic is an effective (r      ) for the cold.",
"The (s      ) include headache and loss of appetite.",
"(S      ) was pouring down his face.",
"(B      ) have been living on the earth for hundreds of millions of years.",
"We haven't (p      ) for tomorrow's meeting yet.",
"All rooms are (e      ) with video cameras.",
"The hotel is (f      ) with antiques.",
"Beauty and the (B      ) is a well-known children's story.",
"She has a degree in (b      ).",
"(B      ) is the scientific study of plants.",
"Embryos grow by (c      ) division.",
"(E      ) looks into living things and their surroundings.",
"Only birds have (f      ) and they cover most of their body.",
"The (f      ) of a mammal keeps it warm in cold weather.",
"(I      ) flew in every time I opened the window.",
"All animals have a strong (i      ) for survival.",
"Darwin explained how (e      ) takes place.",
"He was (e      ) at Bristol University.",
"I still can't (c      ) what happened.",
"The study (e      ) the effects of unemployment.",
"If you travel overseas, you'll learn a lot about (c      ) differences.",
"I like (f      ) dancing and (f      ) music.",
"We want a clean and healthy environment for all (h      ).",
"The local (i      ) are against the plan to build a shopping center.",
"Conditions at the camp were very (p      ).",
"Police are looking for the (s      ) killer of five men.",
"They treated her like a (s      ).",
"The (t      ) members were wearing traditional costumes.",
"My friend has a very interesting (e      ) background.",
"A lot of factory work is done by (m      ) workers.",
"Children quickly learn to (d      ) right from wrong.",
"The team manager's position will be (r      ) at the end of the season.",
"Plants (a      ) nutrients from the soil.",
"My brother has been (a      ) in playing video games these days.",
"(C      ) are eating grass in the field.",
"Lots of rain, a hot climate and (f      ) soil can produce good rice.",
"The (p      ) caused 100,000 deaths in London alone in the 1600s.",
"My brother seems bored with (r      ) life.",
"I've been pulling (w      ) in the backyard.",
"Australia exports (w      ) to many countries.",
"Bread, cakes, and pasta are made from (f      ).",
"The quality of the soil partially determines the crop's (y      ).",
"Finally he (y      ) to temptation.",
"(O      ) farming is better for the environment.",
"Please (b      ) these sticks together with rope.",
"Alan (g      ) the handle of the door and pulled.",
"He (h      ) the situation very well.",
"My mother (s      ) some lemon juice on the salad.",
"There are five (c      ) in the coming election.",
"The country has been torn apart by (c      ) war.",
"The U.S. President gave a speech to (C      ).",
"The Japanese (C      ) says that we will never start a war.",
"The Netherlands is a (k      ) in the northwestern part of Europe.",
"Give me (l      ), or give me death.",
"You are at (l      ) to say anything you like at this meeting.",
"The country is prepared to use (m      ) force.",
"She (s      ) her coffee with a spoon.",
"Brad (t      ) the letter to pieces and threw them in a trash can.",
"The waiter was (w      ) the tables.",
"She (s      ) two more sweaters into her bag.",
"The bill was passed by (P      ) in April.",
"Education is now a major (p      ) issue.",
"Nine (r      ) took part in the referendum.",
"The Russian foreign (m      ) was also present at the meeting.",
"There has been a (r      ) in the education system.",
"They have signed a (t      ) reducing long-range missiles.",
"To everyone's surprise, the famous actor was elected (g      ) of that state.",
"We're going to the computer (c      ) in San Francisco next month.",
"Slavery was (a      ) in the U.S. in the 19th country.",
"He has been (a      ) of murder.",
"He (c      ) the crime of driving under the influence of alcohol.",
"He (i      ) a fortune from his grandfather.",
"There is incredible energy stored inside an (a      ).",
"Scientists have collected a (m      ) of data.",
"The U.S. Navy has many (n      )-powered submarines.",
"(O      ) is essential for life.",
"(H      ) is the lightest of all gases.",
"We know that the earth is not a true (s      ).",
"Each sample was examined with a (m      ).",
"Sodium (c      ), our common table salt, is essential to human life.",
"(A      ) rain will become an even more controversial issue in the near future.",
"I was (a      ) as chairperson.",
"The same party has (g      ) the country for twelve years.",
"The government (i      ) a new tax on cigarettes.",
"She works in the financial (d      ).",
"What effects has (g      ) had on the population?",
"We export our goods all over the (g      ).",
"The Statue of Liberty stands on an island in the (h      ) of New York City.",
"Squalls are common in tropical (r      ).",
"This is the quickest (r      ) to the station.",
"Hong Kong became Chinese (t      ) again in 1997.",
"The problem of air pollution is especially serious in (u      ) areas.",
"Students may choose from a wide (r      ) of subjects.",
"A great number of people (p      ) against the war.",
"Many people (o      ) the new law.",
"Please don't (i      ) me when I'm talking.",
"The rain may (i      ) with our plans to go hiking.",
"Everyone (m      ) (f      ) (o      ) my clothes.",
"She (m      ) (u      ) the whole story.",
"I don't eat breakfast, but I (m      ) (u      ) (f      ) it at lunch.",
"We must (m      ) (a      ) (f      ) the criminal's age.",
"I (m      ) (i      ) (a      ) (r      ) not (t      ) mix business with pleasure.",
"Have you (w      ) (o      ) the schedule for next month?",
"She was about to ask another question when George (c      ) (i      ).",
"We (p      ) (u      ) in front of the restaurant.",
"You can't be serious. You're (p      ) (m      ) (l      ).",
"I think we've (h      ) (o      ) a problem.",
"We (f      ) (o      ) over the education of our children.",
"The movie didn't really (l      ) (u      ) (t      ) our expectations.",
"He should be made to (a      ) (f      ) his crimes.",
"I need to (c      ) (m      ) (s      ) because I spilled coffee on it.",
"You need to (c      ) (t      ) at Shinjuku Station.",
"It's the custom to (s      ) (h      ) at the beginning of an interview.",
"Technologically, our equipment is a bit (b      ) (t      ) (t      ).",
"No survivors have been found (a      ) (o      ) (y      ).",
"You had better get the concert tickets (i      ) (a      ).",
"If I leave now, I'll be back (i      ) (n      ) (t      ).",
"Summer vacation will be over (b      ) (l      ).",
"The evil empire was gone (f      ) (g      ).",
"We (w      ) (f      ) go for a walk in the park.",
"My parents (w      ) (l      ) (t      ) meet you.",
"You (c      ) (b      ) (t      ) careful when you ride a bicycle at night.",
"I (c      ) thank you (e      ).",
"You (m      ) (w      ) get angry with him.",
"There's nothing happening so we (m      ) (a      ) (w      ) go home.",
"You (m      ) (a      ) (w      ) throw your money away (a      ) spend it on such nonsense.",
"(H      ) (d      ) you speak to me like that?",
"Who (i      ) (i      ) (c      ) (w      ) the project?",
"Teaching children discipline (i      ) (u      ) (t      ) their parents.",
"Smith (i      ) (y      ) (t      ) score a point.",
"My uncle (i      ) (w      ) (o      ), but he lives quite simply.",
"Let's go shopping after you (a      ) (t      ) (w      ) the dishes.",
"An investigation (i      ) (u      ) (w      ) to discover the cause of the train crash.",
"I (a      ) already (a      ) (h      ) (i      ) the new apartment.",
"Recently I have (b      ) (o      ) (g      ) (t      ) (w      ) my neighbors.",
"The President promised to lower income taxes, and he has (b      ) (a      ) (g      ) (a      ) (h      ) (w      ).",
"What you are saying (i      ) (b      ) (t      ) (p      ).",
"I was (n      ) (s      ) (m      ) angry (a      ) worried.",
"They did (n      ) (s      ) (m      ) (a      ) say goodbye when they left.",
"I think cherry blossoms are (a      ) beautiful (a      ) (a      ) flower in Japan.",
"(A      ) (m      ) (a      ) two million visitors come here every year.",
"You can come with us, (p      ) (t      ) you pay for your own meals.",
"Two employees agreed to speak to us (o      ) (c      ) (t      ) they not be named.",
"I'll never speak to her again -- (e      ) (i      ) she apologizes.",
"(A      ) the car's old, it still runs well.",
"You can't get the tickets (u      ) you book them in advance.",
"(S      ) (a      ) it is, this is an object of enormous value.",
"The old system was complicated, (w      ) the new system is very simple.",
"(W      ) you agree (o      ) (n      ), we're going to do it.",
"Opinion polls show that (n      ) (m      ) (t      ) 30 percent of the people trust the government.",
"I talked with her for (n      ) (m      ) (t      ) half an hour.",
"He has (n      ) (l      ) (t      ) three hundred CDs.",
"It will take (n      ) (l      ) (t      ) forty minutes to walk to the station from here.",
"Flying a plane (i      ) (n      ) (m      ) easy (t      ) driving a car (i      ).",
"Watt (w      ) (n      ) (l      ) a genius (t      ) Edison (w      ).",
"We flew to Rio de Janeiro (b      ) (w      ) (o      ) Frankfurt.",
"Walter promised to return the money (w      ) (f      ).",
"The movie was great, (a      ) (f      ) the silly ending.",
"This type of even isn't (t      ) (e      ) (t      ).",
"I'll call her tomorrow -- no, (o      ) (s      ) (t      ), I'll try now.",
"They say that the bicycle thieves are still (a      ) (l      ).",
"Don't criticize him (b      ) (h      ) (b      ).",
"(T      ) (m      ) you sleep, (t      ) (m      ) relaxed you'll feel.",
"My mother looks (a      ) (t      ) (b      ) (f      ) taking three days off from work.",
"My job has become (n      ) (t      ) (e      ) (b      ) of the new assistant.",
"She (k      ) (b      ) (t      ) (t      ) argue with him when he used that particular tone of voice.",
"She (i      ) (i      ) (i      ) starting her own business.",
"The legend (i      ) (k      ) (t      ) everyone in this village.",
"A man (i      ) (n      ) (b      ) the company he keeps.",
"The old desk of mine (w      ) (c      ) (w      ) dust.",
"We (w      ) (c      ) (i      ) a heavy snowstorm."]

E = ["labor",
"job",
"task",
"profession",
"occupation",
"carriage",
"freight",
"load",
"wheel",
"hard",
"hardly",
"Just",
"justly",
"late",
"lately",
"near",
"nearly",
"living",
"priceless",
"worthless",
"very",
"most",
"mostly",
"pretty",
"prettily",
"sharp",
"sharply",
"figures",
"sum",
"quantity",
"quarter",
"doubled",
"transported",
"transfer",
"wandering",
"shifted",
"depart",
"conveyed",
"descend",
"immigrated",
"chairperson",
"conference",
"financial",
"firm",
"item",
"manager",
"secretary",
"signature",
"undertook",
"fulfilled",
"established",
"construct",
"maintain",
"engaged",
"slip",
"staff",
"suit",
"manual",
"deal",
"deal",
"brand",
"congratulated",
"assured",
"declared",
"illustrate",
"demonstrated",
"exhibited",
"holy",
"mercy",
"religious",
"sins",
"faith",
"belief",
"glory",
"sacred",
"eternal",
"worshipped",
"pray",
"blessed",
"confessed",
"sacrifice",
"court",
"lawyer",
"proof",
"victims",
"Witnesses",
"trial",
"Fog",
"floods",
"typical",
"breeze",
"frost",
"moist",
"humid",
"thermometer",
"thunder",
"contract",
"innocent",
"justice",
"legal",
"prison",
"exposed",
"emerge",
"revealed",
"imply",
"arose",
"generates",
"ache",
"ambulance",
"comfort",
"deaf",
"drug",
"fatigue",
"Muscle",
"remedy",
"symptoms",
"Sweat",
"Bacteria",
"prepared",
"equipped",
"furnished",
"Beast",
"biology",
"Botany",
"cell",
"Ecology",
"feathers",
"fur",
"Insects",
"instinct",
"evolution",
"educated",
"comprehend",
"examines",
"cultural",
"folk folk",
"humanity",
"inhabitants",
"primitive",
"savage",
"slave",
"tribe",
"ethnic",
"migrant",
"distinguish",
"reviewed",
"absorb",
"absorbed",
"Cattle",
"fertile",
"plague",
"rural",
"weeds",
"wheat",
"flour",
"yield",
"yielded",
"Organic",
"bind",
"grasped",
"handled",
"squeezed",
"candidates",
"civil",
"Congress",
"Constitution",
"kingdom",
"liberty",
"liberty",
"military",
"stirred",
"tore",
"wiping",
"stuffed",
"Parliament",
"political",
"republics",
"minister",
"revolution",
"treaty",
"governor",
"convention",
"abolished",
"accused",
"committed",
"inherited",
"atom",
"mass",
"nuclear",
"Oxygen",
"Hydrogen",
"sphere",
"microscope",
"chloride",
"Acid",
"appointed",
"governed",
"imposed",
"district",
"geography",
"globe",
"harbor",
"regions",
"route",
"territory",
"urban",
"range",
"protested",
"opposed",
"interrupt",
"interfere",
"made fun of",
"made up",
"make up for",
"make allowances for",
"make it a rule to",
"worked out",
"cut in",
"pulled up",
"pulling my leg",
"hit on",
"fell out",
"live up to",
"answer for",
"change my shirt",
"change trains",
"shake hands",
"behind the times",
"as of yet",
"in advance",
"in no time",
"before long",
"for good",
"would often",
"would like to",
"cannot be too",
"cannot enough",
"may well",
"may as well",
"may as well as",
"How dare",
"is in charge of",
"is up to",
"is yet to",
"is well off",
"are through with",
"is under way",
"am at home in",
"been on good terms with",
"been as good as his word",
"is beside the point",
"not so much as",
"not so much as",
"as as any",
"As many as",
"provided that",
"on condition that",
"even if",
"Although",
"unless",
"Small as",
"whereas",
"Whether or not",
"no more than",
"not more than",
"no less than",
"not less than",
"is no more than is",
"was no less than was",
"by way of",
"without fail",
"apart from",
"to everyone's taste",
"on second thought",
"at large",
"behind his back",
"The more the more",
"all the better for",
"none the easier because",
"knew better than to",
"is interested in",
"is known to",
"is known by",
"was covered with",
"were caught in"]

Qnum = int(input("問題数?: "))

num = [i for i in range(len(E))]
random.shuffle(num)

wrong_list = []
score = 0

for i in range(Qnum):
 print(i + 1)
 print(J[num[i]])
 print(E_sentence[num[i]])
 ans = input()
 if ans == E[num[i]]:
  print("Correct.")
  score += 1
 else:
 	print("Wrong.")
 	print("Ans:", E[num[i]])
 	wrong_list.append(num[i])
 print()
 print()

wrong_list.sort()

print("RESULT:")
print(score, "/", Qnum)
print([E[i] for i in wrong_list])
if score == Qnum:
 print("Perfect!")
